### ISSUE TITLE
kernel not found in checkpoint

### ISSUE THREAD

**Issue by kriskrishnaa** [mlberkeley/oreilly-captions#20]
Using TensorFlow backend.
(158915, 4096)
(158915,)
Two young guys with shaggy hair look at their hands while hanging out in the yard .
preprocessing 30 word vocab
preprocessed words 20326 -> 2942
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1306, in _run_fn
    status, run_metadata)
  File "C:\Program Files\Python36\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Key RNN/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/SONY/Desktop/img_cap/training.py", line 206, in <module>
    train(.001,True,True)    #continue training from pretrained weights @epoch500
  File "C:/Users/SONY/Desktop/img_cap/training.py", line 176, in train
    saver.restore(sess,tf.train.latest_checkpoint(model_path_transfer))
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    options, run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key RNN/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]

Caused by op 'save/RestoreV2_1', defined at:
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python36\lib\idlelib\run.py", line 144, in main
    ret = method(*args, **kwargs)
  File "C:\Program Files\Python36\lib\idlelib\run.py", line 474, in runcode
    exec(code, self.locals)
  File "C:/Users/SONY/Desktop/img_cap/training.py", line 206, in <module>
    train(.001,True,True)    #continue training from pretrained weights @epoch500
  File "C:/Users/SONY/Desktop/img_cap/training.py", line 165, in train
    saver = tf.train.Saver(max_to_keep=100)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1140, in __init__
    self.build()
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1172, in build
    filename=self._filename)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 688, in build
    restore_sequentially, reshape)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 663, in restore_v2
    dtypes=dtypes, name=name)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key RNN/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]

**# please resolve this!**

**Comment by chandanmishra-03** [comment]
I am facing same problem.can anyone help?

**Comment by mohitbindal10** [comment]
it seems the model was trained on previous version of tf having a bit different layer architectures. i am training my own model and will ask for pull once it is trained upto good accuracy. And btw if u train your own model keep batch sizes to minimum. The model tends to diverge on larger batch sizes

**Comment by chandanmishra-03** [comment]
Hey I used docker method.Its easy.try it ,you will not get error.

**Comment by wangzhanxd** [comment]
do you solve it?

**Comment by kriskrishnaa** [comment]
Not yet!
